services:
  kafka-1:
    image: apache/kafka:4.0.0
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT= yes
      - KAFKA_NODE_ID= 1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CLUSTER_ID= sCZ1aNbST8mFeSYg3B9m-w
      - KAFKA_LOG_DIRS= /var/lib/kafka/data
    volumes:
      - kafka1_data:/var/lib/kafka/data

  kafka-2:
      image: apache/kafka:4.0.0
      container_name: kafka-2
      ports:
        - "9093:9093"
      environment:
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_NODE_ID=2
        - KAFKA_PROCESS_ROLES=broker,controller
        - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
        - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
        - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CLUSTER_ID= sCZ1aNbST8mFeSYg3B9m-w
        - KAFKA_LOG_DIRS= /var/lib/kafka/data
      volumes:
        - kafka2_data:/var/lib/kafka/data

  kafka-3:
        image: apache/kafka:4.0.0
        container_name: kafka-3
        ports:
          - "9094:9094"
        environment:
          - KAFKA_ENABLE_KRAFT=yes
          - KAFKA_NODE_ID=3
          - KAFKA_PROCESS_ROLES=broker,controller
          - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
          - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9094
          - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
          - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
          - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
          - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
          - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
          - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2
          - ALLOW_PLAINTEXT_LISTENER=yes
          - KAFKA_CLUSTER_ID= sCZ1aNbST8mFeSYg3B9m-w
          - KAFKA_LOG_DIRS= /var/lib/kafka/data

        volumes:
          - kafka3_data:/var/lib/kafka/data

volumes:
      kafka1_data:
      kafka2_data:
      kafka3_data: